const products = [
  {
    id: 1,
    name: 'Apple',
    description: 'Fresh red apple from local farms.',
    location: 'New York',
    category: 'Fruits',
    price: 0.99,
  },
  {
    id: 2,
    name: 'Banana',
    description: 'Ripe yellow bananas, perfect for smoothies.',
    location: 'Los Angeles',
    category: 'Fruits',
    price: 0.49,
  },
  {
    id: 3,
    name: 'Carrot',
    description: 'Organic carrots, rich in vitamins.',
    location: 'Chicago',
    category: 'Vegetables',
    price: 0.79,
  },
  {
    id: 4,
    name: 'Broccoli',
    description: 'Fresh green broccoli, great for stir-fries.',
    location: 'New York',
    category: 'Vegetables',
    price: 1.49,
  },
  {
    id: 5,
    name: 'Rice',
    description: 'Long-grain white rice, perfect for any meal.',
    location: 'Los Angeles',
    category: 'Grains',
    price: 2.99,
  },
  {
    id: 6,
    name: 'Strawberry',
    description: 'Sweet and juicy strawberries.',
    location: 'Chicago',
    category: 'Fruits',
    price: 3.99,
  },
  {
    id: 7,
    name: 'Spinach',
    description: 'Fresh spinach, great for salads.',
    location: 'New York',
    category: 'Vegetables',
    price: 2.49,
  },
  {
    id: 8,
    name: 'Oats',
    description: 'Rolled oats, perfect for breakfast.',
    location: 'Los Angeles',
    category: 'Grains',
    price: 3.49,
  },
  {
    id: 9,
    name: 'Blueberry',
    description: 'Fresh blueberries, rich in antioxidants.',
    location: 'Chicago',
    category: 'Fruits',
    price: 4.99,
  },
  {
    id: 10,
    name: 'Wheat',
    description: 'Whole wheat grains.',
    location: 'New York',
    category: 'Grains',
    price: 5.99,
  },
    {
    id: 11,
    name: 'Cucumber',
    description: 'Fresh cucumbers, perfect for salads.',
    location: 'Los Angeles',
    category: 'Vegetables',
    price: 1.99,
  },
    {
    id: 12,
    name: 'Mango',
    description: 'Sweet and juicy mangos.',
    location: 'Chicago',
    category: 'Fruits',
    price: 2.99,
  },
];

export default products;